stage: pt
do_train: true
finetuning_type: full

packing: true
cutoff_len: 512

per_device_train_batch_size: 2
gradient_accumulation_steps: 16

learning_rate: 5.0e-5
lr_scheduler_type: cosine
warmup_ratio: 0.1
weight_decay: 0.1

bf16: true
fp16: false

logging_steps: 10
save_steps: 1000000
plot_loss: true

preprocessing_num_workers: 8
overwrite_cache: false
report_to: none